import Head from 'next/head'
import Image from 'next/image'
import styles from '../../../styles/TripEdit.module.scss'
import {Trip} from '../../../types'
import LeftNavBar from '../../../components/LeftNavbar'
import MobileHeader from '../../../components/MobileHeader'
import Link from "next/link";

const token = 'eGFBGlRBZB5ics8E2WzZ';

type Props = {
    trips: Trip[],
    trip: Trip
}

export default function Id({trips, trip}: Props) {

    const tripsList = trips.map((t, index) => <div className={styles.trip} key={index}>
        <div className={styles.tripDetails}>
            <div className={styles.countryLogo}>
                <Image src="/austria.svg" alt="austria" width={48} height={48}/>
            </div>
            <div>
                <div className={styles.firstRow}>
                    <div className={styles.country}>
                        {t.address.country}
                    </div>
                    <div className={styles.date}>
                        {t.start_date} - {t.end_date}
                    </div>
                </div>
                <div className={styles.secondRow}>
                    <div className={styles.company}>
                        {t.company_name}
                    </div>

                    <div className={styles.address}>
                        {t.address.street}
                    </div>
                </div>
            </div>
        </div>
        <div className={styles.buttons}>
            <button className={styles.removeBtn}>
                <Image src="/remove.svg" alt="remove" width={10} height={16}/>
            </button>
            <Link href="/trips/trip">
                <button className={styles.okBtn}>
                    <Image src="/arrowRight.svg" alt="arrowRight" width={10} height={16}/>
                </button>
            </Link>
        </div>
    </div>);


    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <LeftNavBar/>

                <div className={styles.content}>
                    <MobileHeader label="View trip"/>
                    <div className={styles.header}>
                        <h1 className={styles.title}>
                            View trip

                        </h1>
                    </div>

                    <div className={styles.formFragment}>
                        <span>
                            Where do you want to go
                        </span>
                        <input disabled={true} value={trip.address.country}/>

                    </div>

                    <div className={styles.formFragment}>
                        <span>
                            Start date
                        </span>
                        <input disabled={true} value={trip.start_date}/>

                        <span>
                            End date
                        </span>
                        <input disabled={true} value={trip.end_date}/>
                    </div>
                </div>
                <div className={styles.tripsList}>
                    {tripsList}
                </div>

            </main>

        </div>
    )
}

export async function getStaticProps(context) {
    const res1 = await fetch('https://task-devel.cleevio-vercel.vercel.app/api/trip', {
        headers: new Headers({
            'Authorization': 'Bearer ' + token,
        }),
    })
    const trips = await res1.json();

    const res2 = await fetch('https://task-devel.cleevio-vercel.vercel.app/api/trip/' + context.params.id, {
        headers: new Headers({
            'Authorization': 'Bearer ' + token,
        }),
    })
    const trip = await res2.json();

    return {
        props: {
            trips,
            trip,
        },
    }
}

export async function getStaticPaths() {
    const res = await fetch('https://task-devel.cleevio-vercel.vercel.app/api/trip', {
        headers: new Headers({
            'Authorization': 'Bearer ' + token,
        }),
    })
    const trips = await res.json()
    const paths = trips.map(t => ({
        params: {
            id: t.id
        }
    }));

    return {
        paths,
        fallback: false
    }
}